import { StyleSheet, Dimensions } from 'react-native';
import { darkColors, fonts, lightColors, radius, spacing } from './theme';

/**
 * Backwards-compatible style layer.
 *
 * The restyled screens use the themed components in `components/ui` and the
 * tokens in `constants/theme.ts`. This file keeps every key that existed in the
 * original `globalStyles` / `COLORS` (with refreshed values) so any screen that
 * still imports it continues to compile and picks up the new look in light mode.
 */

const { width, height } = Dimensions.get('window');

export const COLORS = {
  // Backgrounds
  background: lightColors.background,
  backgroundLight: lightColors.surface,
  backgroundDark: lightColors.surfaceMuted,

  // Primary (Burgundy)
  primary: lightColors.primary,
  primaryLight: lightColors.primarySoft,
  primaryDark: lightColors.primaryPressed,

  // Accent (Gold)
  accent: lightColors.accent,
  accentLight: lightColors.accentSoft,
  accentDark: lightColors.accentStrong,

  // Secondary (Deep plum-brown text)
  secondary: lightColors.text,
  secondaryLight: lightColors.surfaceAlt,
  secondaryDark: lightColors.text,

  // Highlight (used for errors/emphasis)
  highlight: lightColors.danger,
  highlightLight: lightColors.dangerSoft,
  highlightDark: lightColors.primaryPressed,

  // Essentials
  white: '#FFFFFF',
  text: lightColors.text,
  muted: lightColors.textMuted,
  border: lightColors.border,
  headerBackgroundColor: lightColors.headerBackground,
  headerBackgroundColorDark: darkColors.headerBackground,

  // Aliases (kept for older screens)
  rose: lightColors.primary,
  gold: lightColors.accent,
  brown: lightColors.text,
  hoverPink: lightColors.primaryPressed,
};

const cardShadow = {
  shadowColor: lightColors.shadow,
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.08,
  shadowRadius: 16,
  elevation: 3,
} as const;

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 50,
    paddingBottom: 10,
    backgroundColor: COLORS.background,
  },
  pageText: {
    fontFamily: fonts.serifItalic,
    fontSize: 24,
    lineHeight: 34,
    color: COLORS.text,
    textAlign: 'center',
    paddingHorizontal: spacing.xxl,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: spacing.xxl,
    paddingBottom: 120,
  },
  title: {
    fontFamily: fonts.serifSemiBold,
    fontSize: 28,
    lineHeight: 34,
    color: COLORS.text,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: fonts.sans,
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.muted,
    marginBottom: spacing.xxl,
    textAlign: 'center',
  },
  paragraph: {
    margin: spacing.xxl,
    fontFamily: fonts.serifSemiBold,
    fontSize: 24,
    textAlign: 'center',
    color: COLORS.text,
  },
  button: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    paddingHorizontal: spacing.xxl,
    borderRadius: radius.pill,
    marginBottom: spacing.md,
    width: '85%',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 4,
  },
  buttonContainer: {
    marginVertical: spacing.md,
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.white,
    fontFamily: fonts.sansSemiBold,
    fontSize: 16,
  },
  logoImage: {
    height: height / 5,
    width: width / 1.5,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  textInputView: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.backgroundLight,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: radius.md,
    height: 52,
    marginTop: spacing.lg,
    width: '85%',
    alignSelf: 'center',
    paddingHorizontal: spacing.md,
  },
  textInputStyle: {
    flex: 1,
    fontFamily: fonts.sans,
    fontSize: 16,
    color: COLORS.text,
  },
  signinButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: radius.pill,
    marginTop: spacing.xxl,
    width: '85%',
    alignSelf: 'center',
  },
  signinButtonText: {
    textAlign: 'center',
    color: COLORS.white,
    fontFamily: fonts.sansSemiBold,
    fontSize: 16,
  },
  signupText: {
    textAlign: 'center',
    marginTop: spacing.xxl,
    fontFamily: fonts.sans,
    color: COLORS.muted,
  },
  signupLink: {
    color: COLORS.primary,
    fontFamily: fonts.sansSemiBold,
  },
  signupButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: radius.pill,
    marginTop: spacing.xxl,
    width: '85%',
    alignSelf: 'center',
  },
  signupButtonText: {
    textAlign: 'center',
    color: COLORS.white,
    fontFamily: fonts.sansSemiBold,
    fontSize: 16,
  },
  loginText: {
    textAlign: 'center',
    marginTop: spacing.xxl,
    fontFamily: fonts.sans,
    color: COLORS.muted,
  },
  loginLink: {
    color: COLORS.primary,
    fontFamily: fonts.sansSemiBold,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginVertical: spacing.xxl,
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  iconSymbol: {
    fontSize: 28,
    color: COLORS.primary,
    textAlign: 'center',
  },
  iconCircle: {
    width: 72,
    height: 72,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.backgroundLight,
    ...cardShadow,
  },
  selectBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: radius.md,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    marginVertical: spacing.lg,
    alignSelf: 'center',
    width: '92%',
    backgroundColor: COLORS.backgroundLight,
    ...cardShadow,
  },
  selectBoxText: {
    fontFamily: fonts.serifSemiBold,
    fontSize: 20,
    color: COLORS.text,
    textAlign: 'center',
  },
  questionfixedHeader: {
    backgroundColor: COLORS.background,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    zIndex: 10,
  },
  tabContainer: {
    backgroundColor: COLORS.background,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
    paddingHorizontal: spacing.lg,
  },
  tabWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: spacing.sm,
    columnGap: spacing.sm,
  },
  tab: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    minHeight: 38,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.backgroundLight,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  activeTab: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  tabText: {
    fontFamily: fonts.sansMedium,
    fontSize: 14,
    lineHeight: 18,
    color: COLORS.text,
    textAlign: 'center',
  },
  activeTabText: {
    fontFamily: fonts.sansSemiBold,
    color: COLORS.white,
  },
  questionList: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: spacing.xxxl,
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    width: '92%',
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginVertical: spacing.xs,
    ...cardShadow,
  },
  questionItem: {
    width: '92%',
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginVertical: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    ...cardShadow,
  },
  questionNumber: {
    fontFamily: fonts.sansSemiBold,
    fontSize: 14,
    color: COLORS.primary,
    width: 32,
    textAlign: 'right',
    marginRight: spacing.sm,
  },
  questionText: {
    fontFamily: fonts.sans,
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.text,
    flex: 1,
    paddingLeft: spacing.xs,
  },
  section: {
    marginBottom: spacing.xxxl,
    width: '90%',
  },
  sectionTitle: {
    fontFamily: fonts.sansSemiBold,
    fontSize: 12,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    marginBottom: spacing.md,
    color: COLORS.muted,
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.backgroundLight,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: spacing.sm,
  },
  settingLabel: {
    fontFamily: fonts.sans,
    fontSize: 16,
    color: COLORS.text,
  },
  linkButton: {
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
  },
  linkText: {
    color: COLORS.text,
    fontFamily: fonts.sansMedium,
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(43, 26, 30, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xxl,
  },
  modalContent: {
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.xl,
    padding: spacing.xxxl,
    alignItems: 'center',
    width: '100%',
    ...cardShadow,
  },
  quoteText: {
    fontFamily: fonts.serifItalic,
    fontSize: 22,
    lineHeight: 32,
    color: COLORS.text,
    marginBottom: spacing.xxl,
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: spacing.xxl,
    borderRadius: radius.pill,
    marginBottom: spacing.sm,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  saveButtonText: {
    color: COLORS.white,
    fontFamily: fonts.sansSemiBold,
    fontSize: 16,
  },
  closeButton: {
    paddingVertical: 12,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.pill,
    backgroundColor: COLORS.secondaryLight,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  closeButtonText: {
    color: COLORS.primary,
    fontFamily: fonts.sansSemiBold,
    fontSize: 15,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: width,
    backgroundColor: COLORS.background,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  footerText: {
    fontFamily: fonts.sans,
    fontSize: 12,
    color: COLORS.muted,
    textAlign: 'center',
  },
  card: {
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    width: '90%',
    alignSelf: 'center',
    ...cardShadow,
  },
  cardTitle: {
    fontFamily: fonts.serifSemiBold,
    fontSize: 18,
    color: COLORS.text,
    marginBottom: spacing.sm,
  },
  cardText: {
    fontFamily: fonts.sans,
    fontSize: 15,
    lineHeight: 22,
    color: COLORS.text,
    marginBottom: spacing.xs,
  },
  cardLabel: {
    fontFamily: fonts.sansSemiBold,
    color: COLORS.muted,
  },
  errorText: {
    color: COLORS.highlight,
    marginTop: spacing.sm,
    textAlign: 'center',
    fontFamily: fonts.sans,
    fontSize: 15,
  },
  pickerContainer: {
    width: '80%',
    alignContent: 'center',
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    marginLeft: '10%',
    marginBottom: spacing.xxl,
    ...cardShadow,
  },
  pickerLabel: {
    fontFamily: fonts.sansMedium,
    fontSize: 14,
    color: COLORS.muted,
    marginBottom: spacing.sm,
  },
  pickerText: {
    fontFamily: fonts.serifSemiBold,
    fontSize: 18,
    color: COLORS.text,
    textAlign: 'center',
  },
  dateTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  dateTimePicker: {
    marginHorizontal: spacing.sm,
    backgroundColor: COLORS.secondaryLight,
    borderRadius: radius.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
  },
  dateTimeText: {
    fontFamily: fonts.serifSemiBold,
    fontSize: 18,
    color: COLORS.text,
    textAlign: 'center',
  },
  dobbutton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: radius.pill,
    marginTop: spacing.sm,
    width: '80%',
    alignItems: 'center',
    alignSelf: 'center',
  },
  datePickerContainer: {
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    marginVertical: spacing.md,
    marginHorizontal: spacing.xl,
    ...cardShadow,
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: spacing.xxl,
    borderRadius: radius.pill,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    marginBottom: spacing.xl,
    width: 'auto',
    alignItems: 'center',
  },
  buttonOutlineText: {
    color: COLORS.primary,
    fontFamily: fonts.sansSemiBold,
    fontSize: 15,
  },
  label: {
    fontFamily: fonts.sansMedium,
    fontSize: 14,
    color: COLORS.muted,
    marginBottom: spacing.sm,
    alignSelf: 'flex-start',
    marginLeft: '7.5%',
  },
  profileCard: {
    backgroundColor: COLORS.backgroundLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: spacing.xl,
    marginHorizontal: spacing.xl,
    marginBottom: spacing.xxxl,
    ...cardShadow,
  },
  profiletext: {
    fontFamily: fonts.serifSemiBold,
    fontSize: 24,
    color: COLORS.text,
  },
  profileLabel: {
    fontFamily: fonts.sansSemiBold,
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: COLORS.muted,
    marginTop: spacing.md,
  },
  profileValue: {
    fontFamily: fonts.sans,
    fontSize: 17,
    color: COLORS.text,
    marginBottom: spacing.xs,
  },
  noProfileDataText: {
    fontFamily: fonts.serifItalic,
    fontSize: 16,
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: spacing.xl,
  },
});

export default globalStyles;
