import { StyleSheet, Dimensions } from 'react-native';
import Constants from 'expo-constants';
const { width, height } = Dimensions.get('window');

export const COLORS = {
  // Backgrounds
  background: '#f8f5f0',
  backgroundLight: '#fdfaf6',
  backgroundDark: '#b8a48a',

  // Primary (Deep Rose)
  primary: '#7c3a2f',
  primaryLight: '#f8efef',
  primaryDark: '#3a2121',

  // Accent (Gold)
  accent: '#c9a86a',
  accentLight: '#f9f5e9',
  accentDark: '#7a5a2f',

  // Secondary (Rich Brown)
  secondary: '#4e3629',
  secondaryLight: '#ede6df',
  secondaryDark: '#271d14',

  // Highlight (Rose-Pink)
  highlight: '#b97a7a',
  highlightLight: '#fbeeee',
  highlightDark: '#452828',

  // Essentials
  white: '#fff',
  text: '#4e3629',
  muted: '#b8a48a',
  border: '#c9a86a',
  headerBackgroundColor: '#ebe2d3',
  headerBackgroundColorDark: '#3a2121',

  // Aliases
  rose: '#7c3a2f',
  gold: '#c9a86a',
  brown: '#4e3629',
  hoverPink: '#b97a7a',
};

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 8, //Constants.statusBarHeight,
    backgroundColor: COLORS.backgroundLight,
  },
  pageText: {
    fontSize: 34,
    color: COLORS.text,
    textAlign: 'center',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 80,
    paddingBottom: 120,
  },
  title: {
    fontSize: 34,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 18,
    color: COLORS.secondary,
    marginBottom: 32,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  paragraph: {
    margin: 24,
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    color: COLORS.highlight,
  },
  button: {
    backgroundColor: COLORS.primary,
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
    elevation: 3,
    width: '55%',
    alignItems: 'center',
    shadowColor: COLORS.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  buttonContainer: {
    marginVertical: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  logoImage: {
    height: height / 5,
    width: width / 1.5,
    alignSelf: 'center',
  },
  textInputView: {
    flexDirection: 'row',
    borderBottomColor: COLORS.muted,
    borderBottomWidth: 2,
    height: 30,
    marginTop: 30,
    width: '85%',          
    alignSelf: 'center',
  },
  textInputStyle: {
    flex: 1,
    paddingLeft: 10,
    marginTop: -10,
    fontSize: 14,
    color: COLORS.text,
  },
  signinButton: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    padding: 5,
    borderRadius: 5,
    marginTop: 30,
    width: '55%',      
    alignSelf: 'center',
  },
  signinButtonText: {
    textAlign: 'center',
    color: COLORS.primary,
    fontSize: 14,
  },
  signupText: {
    textAlign: 'center',
    marginTop: 20,
    color: COLORS.muted,
  },
  signupLink: {
    color: COLORS.primary,
    textDecorationLine: 'underline',
  },
  signupButton: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    padding: 5,
    borderRadius: 5,
    marginTop: 30,
    width: '55%',   
  alignSelf: 'center',
  },
  signupButtonText: {
    textAlign: 'center',
    color: COLORS.primary,
    fontSize: 14,
  },
  loginText: {
    textAlign: 'center',
    marginTop: 20,
    color: COLORS.muted,
  },
  loginLink: {
    color: COLORS.primary,
    textDecorationLine: 'underline',
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginVertical: 24,
    gap: 10,
  },
  iconSymbol: {
    fontSize: 20,
    color: COLORS.secondaryDark,
    textAlign: 'center',
    fontWeight: 'bold',
    textShadowColor: COLORS.accent,
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 6,
    letterSpacing: 2,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 6,
    backgroundColor: COLORS.accent,
  },
  selectBox: {
    borderWidth: 2,
    borderColor: COLORS.secondary,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 28,
    marginVertical: 22,
    alignSelf: 'center',
    width: '92%',
    backgroundColor: COLORS.background,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  selectBoxText: {
    fontSize: 24,
    color: COLORS.primary,
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  questionfixedHeader: {
    backgroundColor: COLORS.background, // matches COLORS.backgroundLight
    paddingTop: 4,
    paddingBottom: 4,
    zIndex: 10,
  },
  tabContainer: {
    backgroundColor: '#fdfaf6',
    paddingTop: 12,
    paddingBottom: 4,
    paddingHorizontal: 16, // ⬅️ aligns with question list
  },

  tabWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 10,            // ⬅️ even vertical spacing
    columnGap: 10,         // ⬅️ even horizontal spacing
  },

  tab: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
    minHeight: 38,
    justifyContent: 'center',
    alignItems: 'center',

    backgroundColor: '#f2efe9',
    borderWidth: 1,
    borderColor: '#e2dccf',
  },

  activeTab: {
    backgroundColor: '#efe6d8',
    borderColor: '#c9b8a3',
  },

  tabText: {
    fontSize: 14,
    lineHeight: 18,
    color: '#5a4a3a',
    fontWeight: '500',
    textAlign: 'center',
  },

  activeTabText: {
    fontWeight: '700',
    color: '#3e2f22',
  },

  questionList: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: 32,
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: COLORS.accent,
    paddingVertical: 16,
    width: '92%',
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginVertical: 4,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  questionItem: {
    width: '92%',
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginVertical: 6,
    paddingHorizontal: 12,
    paddingVertical: 16,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  questionNumber: {
    fontSize: 18,
    color: COLORS.highlight,
    width: 32,
    fontFamily: 'serif',
    fontWeight: '600',
    textAlign: 'right',
    marginRight: 8,
  },
  questionText: {
    fontSize: 18,
    color: COLORS.secondary,
    fontFamily: 'serif',
    flex: 1,
    paddingLeft: 4,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
    color: COLORS.text,
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.backgroundLight,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  settingLabel: {
    fontSize: 16,
    color: COLORS.text,
  },
  linkButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  linkText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 18,
    padding: 28,
    alignItems: 'center',
    width: '80%',
    elevation: 8,
  },
  quoteText: {
    fontSize: 20,
    color: COLORS.primary,
    fontStyle: 'italic',
    marginBottom: 24,
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 20,
    marginBottom: 12,
  },
  saveButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  closeButton: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 16,
    backgroundColor: COLORS.background,
  },
  closeButtonText: {
    color: COLORS.primary,
    fontWeight: '600',
    fontSize: 15,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: width,
    backgroundColor: COLORS.secondaryLight,
    paddingVertical: 10,
  },
  footerText: {
    fontSize: 12,
    color: COLORS.secondaryDark,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    width: '90%',
    alignSelf: 'center',
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 8,
  },
  cardText: {
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 4,
  },
  cardLabel: {
    fontWeight: '600',
  },
  errorText: {
    color: COLORS.highlight,
    marginTop: 10,
    textAlign: 'center',
    fontSize: 16,
  },
  pickerContainer: {
    width: '80%',
    alignContent: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.accent,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginLeft: '10%',
    marginBottom: 24,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  pickerLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.secondaryDark,
    marginBottom: 8,
  },
  pickerText: {
    fontSize: 18,
    color: COLORS.text,
    textAlign: 'center',
  },
  dateTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  dateTimePicker: {
    marginHorizontal: 8,
    backgroundColor: COLORS.backgroundLight,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  dateTimeText: {
    fontSize: 16,
    color: COLORS.text,
    textAlign: 'center',
  },
  dobbutton: {
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 20,
    marginTop: 10,
    width: '50%',
    alignItems: 'center',
    alignSelf: 'center',
  },
});

export default globalStyles;
