const QUESTIONS = [
  "Will someone start courting me soon?",
  "Does the man I like think of me too?",
  "Do people still see me as a child?",
  "Does he love me as deeply as I love him?",
  "What can I do to make him happy?",
  "Should I reply to his first message?",
  "What will happen if I go to the meeting?",
  "Should I give in to what he’s asking?",
  "Will my husband be young?",
  "How many husbands will I have?",
  "How many lovers will I have?",
  "What does the person I love really think of me?",
  "Should I believe his sweet words?",
  "Does the one I’m thinking about love me?",
  "Does he know that I love him?",
  "What can I do to make him love me back?",
  "Will I marry at a young age?",
  "Will I have many adventures?",
  "Will my husband make me happy?",
  "Is the man I love faithful to me?",
  "Will my husband suspect me of something?",
  "Should I end it or give in?",
  "Will I have children?",
  "Will I come into money?",
  "Will my secret be revealed?",
  "Do people think I'm attractive?",
  "What do people think of my intelligence?",
  "If my mistake is found out, will I be forgiven?",
  "Will I lose my virginity before marriage?",
  "Will I marry the man I’m currently thinking about?",
  "Will I stay healthy throughout my life?",
  "Should I go ahead with my plan?",
  "Am I paid fairly?",
  "Will I be happy in love?",
  "Will my happiness last long?",
  "Will I marry a wealthy man?",
  "What kind of person will my husband be?",
  "Will my husband be good-looking or not?",
  "Will my husband be intelligent?",
  "Do I have any rivals?",
  "Are the compliments I receive genuine?",
  "Will I be happy in my companies?",
  "How do I stop others from finding out my secret?",
  "Will I marry someone I already know?",
  "How long will our disagreement last?",
  "Will making peace benefit me?",
  "Does my husband love me as much as he did before we married?",
  "Am I the first woman my husband has ever loved?",
  "Has my husband loved anyone else as much as me?",
  "Will the person I’m thinking of come back soon?",
  "Is my husband honest with me?",
  "Will this sadness I feel last much longer?",
  "Will I soon get the news I’m waiting for?",
  "Will my current affair or concern last long?",
  "Which of the two people I’m thinking of should I choose?",
  "Will I receive the gifts I’m expecting?",
  "Will I travel far and often?",
  "Will the relationship I’m in last?",
  "Will my social status change soon?",
  "Will my weakness cause the thing I fear?",
  "Will they keep the promises they made?",
  "Should I forgive them?",
  "Is the apology sincere?",
  "Should I confess everything?",
  "Should I make the first move to make peace?",
  "Does my husband believe I’m truly virtuous?",
  "Should I challenge my husband’s plans?",
  "Am I in danger or distress?",
  "Will I lose any money?",
  "What is the person I’m thinking of doing now?",
  "Is anyone jealous of me?",
  "Will I receive an unexpected inheritance?",
  "Should I be worried about meeting privately?",
  "Will my reputation remain good?",
  "Should I take the advice I was given?",
  "How will my plans turn out?",
  "Will I be loved for a long time?",
  "Will I have a calm or stressful life?",
  "Should I live in the country or the city?",
  "Is there any truth in my fear?",
  "Should I accept the offers being made?",
  "What will happen if I say yes to their request?",
  "Will I die unmarried, married, or widowed?",
  "What job will my husband have?",
  "Will my current wish come true?",
  "Are they thinking about me there?",
  "What do people think of me?",
  "Will I stay single for long?",
  "Will I be happy when I’m old?",
  "When will I stop loving?",
  "Do I have enemies?",
  "Will my wish come true at night or during the day?",
  "Will what I fear happen at night or during the day?",
  "Should I give up worldly pleasures?",
  "Will they regret losing me?",
  "Will I experience more sorrow than joy in the future?",
];

export default QUESTIONS;