import { StyleSheet } from 'react-native';

// Define your color palette
export const COLORS = {
  background: '#ebe2d3',
  primary: '#865456',
  accent: '#ae9263',
  secondary: '#5a4632',
  highlight: '#A97373',
  white: '#fff',
  text: '#5a4632',
  muted: '#ae9263',
  border: '#ae9263',
};

const globalStyles = StyleSheet.create({
  // Generic page container and text
  pageContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: COLORS.background,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  pageText: {
    fontSize: 24,
    color: COLORS.text,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 24,
    justifyContent: 'center',
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  aboutText: {
    fontSize: 12,
    color: COLORS.primary,
    marginLeft: 12,
  },
  
  // Header and title containers
  headerImage: {
    color: COLORS.secondary,
    bottom: -90,
    left: -35,
    position: 'absolute',
  },
  // Home screen styles
  stepContainer: {
    gap: 8,
    marginBottom: 8,
    backgroundColor: COLORS.background,
    borderRadius: 10,
    padding: 10,
  },
  reactLogo: {
    width: 620,
    height: undefined,
    aspectRatio: 620 / 400,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: 16,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  buttonContainer: {
    flexDirection: 'column', // stack vertically
    justifyContent: 'center',
    alignItems: 'stretch',   // make buttons fill the width if desired
    marginVertical: 16,
    gap: 12,                 // space between buttons (React Native >=0.71)
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: 32,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: COLORS.secondary,
    marginBottom: 32,
    textAlign: 'center',
  },
  button: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 30,
    marginBottom: 0,
    elevation: 2,
    width: '100%',
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 24,
    fontWeight: 'bold',
  },
  secondaryButton: {
    borderColor: COLORS.primary,
    borderWidth: 2,
    paddingVertical: 14,
    paddingHorizontal: 36,
    marginBottom: 0,
    borderRadius: 30,
    backgroundColor: COLORS.background,
    width: '100%',
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontSize: 20,
    fontWeight: '600',
  },

  // Profile page styles
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 24,
    backgroundColor: COLORS.muted,
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 8,
  },
  email: {
    fontSize: 16,
    color: COLORS.secondary,
    marginBottom: 32,
  },
  editbutton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 36,
    borderRadius: 30,
    marginBottom: 16,
  },
  logoutButton: {
    borderColor: COLORS.primary,
    borderWidth: 2,
    paddingVertical: 12,
    paddingHorizontal: 36,
    borderRadius: 30,
    backgroundColor: COLORS.background,
  },
  logoutText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginVertical: 24,
    gap: 10,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 6,
    backgroundColor: COLORS.accent,
  },
  selectBox: {
    borderWidth: 2,
    borderColor: COLORS.secondary,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 28,
    marginVertical: 22,
    alignSelf: 'center',
    width: '92%',
    backgroundColor: COLORS.background,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  selectBoxText: {
    fontSize: 24,
    color: COLORS.primary,
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: 'serif',
    letterSpacing: 0.5,
  },
  questionList: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: 32,
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: COLORS.accent,
    paddingVertical: 16,
    width: '92%',
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginVertical: 4,
    shadowColor: COLORS.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  questionNumber: {
    fontSize: 18,
    color: COLORS.highlight,
    width: 32,
    fontFamily: 'serif',
    fontWeight: '600',
    textAlign: 'right',
    marginRight: 8,
  },
  questionText: {
    fontSize: 18,
    color: COLORS.secondary,
    fontFamily: 'serif',
    flex: 1,
    paddingLeft: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 28,
    alignItems: 'center',
    width: '80%',
    elevation: 8,
  },
  quoteText: {
    fontSize: 20,
    color: '#865456',
    fontStyle: 'italic',
    marginBottom: 24,
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: '#865456',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 20,
    marginBottom: 12,
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  closeButton: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 16,
    backgroundColor: '#ebe2d3',
  },
  closeButtonText: {
    color: '#865456',
    fontWeight: '600',
    fontSize: 15,
  },

  // Archive page styles
  archiveContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    paddingTop: 100,
    paddingHorizontal: 0,
  },
  archiveTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 18,
    textAlign: 'center',
  },
  archiveSubtitle: {
    fontSize: 18,
    color: COLORS.secondary,
    textAlign: 'center',
    marginTop: 32,
  },
  archiveScroll: {
    width: '100%',
    paddingHorizontal: 16,
  },
  archiveQuoteBox: {
    marginTop: 32,
    marginBottom: 18,
    padding: 18,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  archiveQuoteText: {
    fontSize: 20,
    color: COLORS.primary,
    fontStyle: 'italic',
    textAlign: 'center',
  },
});

export default globalStyles;